### ISSUE TITLE
Muy buen trabajo!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-lararb#1]
Buen trabajo @lararb !

Algunas pistas para mejorarlo:

- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser h3 sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Revisa los metadatos en index.html (lang, title...)

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by lararb** [comment]
Hola Carlos!
Acabo de terminar los issues, pero me gustaría poner más bonita la app. Dijiste que lo hiciésemos en una nueva rama, pero me surge la duda... hago merge de esa rama con la master? O las dejo separadas para que puedas evaluar bien la master?

**Comment by lararb** [comment]
Además... He querido actualizar la publicación en GitHub Pages (siguiendo los pasos del temario: 1. npm run build 2. mv build docs 3. git add, commit, push) pero ahora se me muestra el Readme y no entiendo por qué si la primera vez que lo hice todo fue bien ¿?

**Comment by oneeyedman** [comment]
Vale, @lararb. Lo damos por completado y ya sigue en master haciendo, y deshaciendo, lo que quieras, sin problema.

Buen trabajo!

**Comment by lararb** [comment]
Genial! Gracias!
